export { default as userService } from './account.service'
export { default as authService } from './auth.service'
export { default as adminService } from './admin.service'
export { default as dashboardService } from './dashboard.service'
export { default as contactService } from './contact.service'
export { default as courseService } from './courses.service'
export { default as faqService } from './faq.service'
export { default as testimonialService } from './testimonial.service'
